// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Domain.Day", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MonthId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("Domain.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("Domain.Month", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthName")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("Domain.Day", b =>
                {
                    b.HasOne("Domain.Month", null)
                        .WithMany("Days")
                        .HasForeignKey("MonthId");
                });

            modelBuilder.Entity("Domain.Habit", b =>
                {
                    b.HasOne("Domain.Day", null)
                        .WithMany("Habits")
                        .HasForeignKey("DayId");
                });

            modelBuilder.Entity("Domain.Day", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("Domain.Month", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
